---
name: Catalyst-Model-Filemaker
version: 0.01
author:
  - 'Michele Ongaro <micheleo@cpan.org>'
abstract: Catalyst model for Filemaker's XML service
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Catalyst::Model: 0
  Catalyst::Utils: 0
  Class::C3: 0
  Net::Filemaker::XML::ResultSet: 0
build_requires:
  Test::More: 0
provides:
  Catalyst::Helper::Model::Filemaker:
    file: lib/Catalyst/Helper/Model/Filemaker.pm
    version: 0.01
  Catalyst::Model::Filemaker:
    file: lib/Catalyst/Model/Filemaker.pm
    version: 0.01
